# Generated by Django 4.0 on 2022-01-27 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('clinic_display', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('actual_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, unique=True)),
                ('region_display', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onhold_hour', models.CharField(blank=True, max_length=50, null=True)),
                ('onhold_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_type', to='hospitals_core.clinic')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_hospital', to='hospitals_core.hospital')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='hospitals_core.region')),
            ],
        ),
    ]
