# Generated by Django 4.0 on 2022-01-26 13:27

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedHospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.CharField(max_length=250)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('onhold_hour', models.CharField(max_length=50)),
                ('hospital_name', models.CharField(max_length=250)),
                ('onhold_date', models.DateField(default=datetime.date.today)),
                ('region', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['hospital_name'],
            },
        ),
    ]
